name: Deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push events for dev and main branches
  push:
    branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Deploy to DEV environment
  deploy-dev:
    name: Deploy to DEV
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to DEV using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IP_HOST}}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/html/dev-blupy-dash/
          git pull origin dev
          npm install
          npm run build
